---
name: CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustc --version
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt -- --check
      - run: cargo check --locked
      - run: cargo clippy --locked
      - run: cargo test --locked -- --include-ignored
      - run: cargo build --locked --release --verbose
      - run: cargo doc --locked --no-deps --release

      - name: add index redirect
        run: make target/doc/index.html
      - run: rm -rfv target/doc/.lock
      - run: find target/debug -name '*.lock' -exec rm -v {} \;
      - uses: actions/upload-pages-artifact@v2
        if: github.event_name != 'pull_request'
        with:
          path: target/doc/

  pages:
    name: CD
    runs-on: ubuntu-latest
    needs: [main]
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
