---
name: CI/CD
on:
  push:
    branches: [master]

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check
      - run: cargo check
      - run: cargo clippy
      - run: cargo test
      - run: cargo build --locked --release --verbose
      - run: cargo doc --release

      - name: add index redirect
        run: make target/doc/index.html
      - run: rm -rf target/doc/.lock
      - run: find target/debug -name '*.lock' -exec rm {} \;
      - uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc/

  pages:
    name: CD
    runs-on: ubuntu-latest
    needs: [main]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
