---
name: Publish
on:
  push:
    tags:
      - "*"

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --locked --release --verbose
      - run: cargo doc --locked --no-deps --release
      - run: cargo vendor --locked
      - run: |
          cp target/release/aoc .
          make target/doc/index.html
          cp -r target/doc .
          rm -rfv doc/.lock
          tar acvf advent-of-code_${{ github.ref_name }}.tar.zst \
            LICENSE README.md aoc doc input vendor
      - uses: ncipollo/release-action@v1
        with:
          artifacts: advent-of-code_*.tar.*
          token: ${{ secrets.GITHUB_TOKEN }}
