---
name: Publish
on:
  push:
    tags:

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --locked --release --verbose
      - run: cargo doc --release
      - run: |
          cp target/release/aoc .
          make target/doc/index.html
          cp -r target/doc .
          rm -rf doc/.lock
          tar acvf advent-of-code_${{ github.ref_name }}.tar.zst \
            LICENSE aoc doc input
      - uses: ncipollo/release-action@v1
        with:
          artifacts: advent-of-code_*.tar.*
          token: ${{ secrets.GITHUB_TOKEN }}
